const State=(()=>{
  const K={user:'se_u',cart:'se_c',wl:'se_w',prods:'se_p',recent:'se_r',cookies:'se_ck',evts:'se_e',tickets:'se_t',orders:'se_o'};
  const ACCS=[
    {email:'user@shopease.com',pw:'password123',name:'Alex Thompson',role:'customer',mkt:true},
    {email:'admin@shopease.com',pw:'admin2025',name:'Admin',role:'admin',mkt:false}
  ];
  const DP=[
    {id:1,name:'Wireless Earbuds',emoji:'🎧',price:49.99,cat:'Electronics',stars:4.4,reviews:1284,stock:24},
    {id:2,name:'Running Shoes',emoji:'👟',price:84.99,cat:'Fashion',stars:4.8,reviews:893,stock:8},
    {id:3,name:'Coffee Maker',emoji:'☕',price:34.99,cat:'Home',stars:4.3,reviews:542,stock:0},
    {id:4,name:'Yoga Mat',emoji:'🧘',price:22.99,cat:'Fitness',stars:4.5,reviews:327,stock:45},
    {id:5,name:'Laptop Stand',emoji:'💻',price:29.99,cat:'Electronics',stars:4.7,reviews:2103,stock:3},
    {id:6,name:'Water Bottle',emoji:'💧',price:14.99,cat:'Fitness',stars:4.4,reviews:672,stock:60},
    {id:7,name:'Desk Lamp',emoji:'💡',price:39.99,cat:'Home',stars:4.2,reviews:435,stock:0},
    {id:8,name:'Backpack',emoji:'🎒',price:59.99,cat:'Fashion',stars:4.6,reviews:1820,stock:15},
    {id:9,name:'Smart Watch',emoji:'⌚',price:129.99,cat:'Electronics',stars:4.5,reviews:3421,stock:10},
    {id:10,name:'Resistance Bands',emoji:'🏋',price:18.99,cat:'Fitness',stars:4.3,reviews:290,stock:30},
    {id:11,name:'Candle Set',emoji:'🕯',price:24.99,cat:'Home',stars:4.7,reviews:762,stock:20},
    {id:12,name:'Sunglasses',emoji:'🕶',price:45.99,cat:'Fashion',stars:4.2,reviews:510,stock:5},
    {id:13,name:'Intel Core i5-14400',emoji:'🔩',price:189.99,cat:'Electronics',stars:4.6,reviews:312,stock:15},
    {id:14,name:'Nvidia RTX 4060',emoji:'🎮',price:299.99,cat:'Electronics',stars:4.7,reviews:528,stock:8},
    {id:15,name:'16GB DDR5 RAM Kit',emoji:'🧠',price:59.99,cat:'Electronics',stars:4.5,reviews:203,stock:30},
    {id:16,name:'1TB NVMe SSD',emoji:'💾',price:74.99,cat:'Electronics',stars:4.8,reviews:874,stock:25},
    {id:17,name:'ATX B760 Motherboard',emoji:'🔧',price:129.99,cat:'Electronics',stars:4.4,reviews:167,stock:10},
    {id:18,name:'650W Modular PSU',emoji:'🔋',price:79.99,cat:'Electronics',stars:4.6,reviews:441,stock:20},
    {id:19,name:'Mid Tower PC Case',emoji:'📦',price:69.99,cat:'Electronics',stars:4.3,reviews:289,stock:12},
    {id:20,name:'120mm CPU Air Cooler',emoji:'💨',price:34.99,cat:'Electronics',stars:4.5,reviews:156,stock:18}
  ];
  function g(k,fb=null){try{const v=localStorage.getItem(k);return v?JSON.parse(v):fb;}catch{return fb;}}
  function s(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch{}}
  function getUser(){return g(K.user);}
  function setUser(u){s(K.user,u);}
  function clearUser(){localStorage.removeItem(K.user);}
  function isAdminArea(){return window.location.pathname.includes('/admin/');}
  function idxPath(){return isAdminArea()?'../index.html':'index.html';}
  function requireAuth(adminOnly=false){
    const u=getUser();
    if(!u){window.location.href=idxPath();return null;}
    if(adminOnly&&u.role!=='admin'){window.location.href='../shop.html';return null;}
    return u;
  }
  function login(email,pw){const a=ACCS.find(x=>x.email===email&&x.pw===pw);if(!a)return null;const u={email:a.email,name:a.name,role:a.role,mkt:a.mkt};setUser(u);return u;}
  function guestLogin(){const u={email:null,name:'Guest',role:'guest',mkt:false};setUser(u);return u;}
  function logout(){clearUser();window.location.href=idxPath();}
  function addAccount(email,pw,name){ACCS.push({email,pw,name,role:'customer',mkt:false});setUser({email,name,role:'customer',mkt:false});}
  function changePw(email,old,nw){const a=ACCS.find(x=>x.email===email);if(!a||a.pw!==old)return false;a.pw=nw;return true;}
  function deleteAccount(email){const i=ACCS.findIndex(x=>x.email===email);if(i>-1)ACCS.splice(i,1);clearUser();s(K.cart,[]);s(K.wl,[]);s(K.recent,[]);}
  function downloadData(u){const d={account:u,cart:getCart(),wishlist:getWL(),recent:getRecent(),exported:new Date().toISOString(),note:'UK GDPR Art.15'};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download='shopease-data.json';a.click();}
  const API='https://shopease-api-bjdvcybfd9aga0h6.canadacentral-01.azurewebsites.net/api';
  function getProds(){return g(K.prods)||JSON.parse(JSON.stringify(DP));}
  function setProds(p){s(K.prods,p);}
  async function syncProds(){try{const r=await fetch(API+'/get-products');const d=await r.json();if(d.products&&Array.isArray(d.products)){s(K.prods,d.products);}}catch{}}
  async function pushProds(token){try{const prods=getProds();await fetch(API+'/save-products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,products:prods})});}catch{}}
  function getCart(){return g(K.cart,[]);}
  function setCart(c){s(K.cart,c);}
  function cartCount(){return getCart().reduce((a,i)=>a+i.qty,0);}
  function cartSub(){return getCart().reduce((a,i)=>a+i.price*i.qty,0);}
  function addToCart(p,qty=1){
    const cart=getCart(),prods=getProds(),pp=prods.find(x=>x.id===p.id);
    if(pp&&pp.stock===0)return false;
    const ex=cart.find(i=>i.id===p.id);
    if(ex){if(pp&&ex.qty>=pp.stock)return false;ex.qty+=qty;}
    else{const item={id:p.id,name:p.name,emoji:p.emoji,price:p.price,cat:p.cat,qty};if(p.image)item.image=p.image;cart.push(item);}
    setCart(cart);track('add_to_cart',{name:p.name,price:p.price});return true;
  }
  function clearCart(){s(K.cart,[]);}
  function getWL(){return g(K.wl,[]);}
  function setWL(w){s(K.wl,w);}
  function toggleWL(id,name){const wl=getWL(),i=wl.indexOf(id);if(i>-1){wl.splice(i,1);setWL(wl);return false;}wl.push(id);setWL(wl);track('wl_add',{name});return true;}
  function getRecent(){return g(K.recent,[]);}
  function addRecent(id){let r=getRecent().filter(x=>x!==id);r.unshift(id);if(r.length>8)r=r.slice(0,8);s(K.recent,r);}
  function getCookies(){return g(K.cookies);}
  function setCookies(lv){s(K.cookies,lv);}
  function getEvts(){return g(K.evts,[]);}
  function track(type,data={}){const e=getEvts();e.push({type,data,ts:Date.now()});if(e.length>2000)e.splice(0,e.length-2000);s(K.evts,e);}
  function clearEvts(){s(K.evts,[]);}
  function getTickets(email){const all=g(K.tickets,{});return email?all[email]||[]:[];}
  function addTicket(ticket){const u=getUser();if(!u||!u.email||u.role==='guest')return;const all=g(K.tickets,{});if(!all[u.email])all[u.email]=[];all[u.email].unshift(ticket);s(K.tickets,all);}
  function getOrders(email){const all=g(K.orders,{});return email?all[email]||[]:[];}
  function addOrder(order,email){const target=email||(getUser()||{}).email;if(!target)return;const all=g(K.orders,{});if(!all[target])all[target]=[];all[target].unshift(order);s(K.orders,all);}
  const SR={
    1:[{r:'Sarah M.',rt:5,ti:'Best earbuds under £50',bo:'Incredible sound quality for the price. Bass is punchy and they stay in my ears during workouts.',vp:true,ts:'2025-11-15T09:00:00Z'},{r:'James R.',rt:4,ti:'Great for commuting',bo:'Solid noise isolation and easy pairing. Battery life is exactly as advertised.',vp:true,ts:'2025-10-28T14:30:00Z'},{r:'Emma T.',rt:4,ti:'Really good value',bo:'Sound quality far exceeds expectations at this price point. Comfortable fit too.',vp:true,ts:'2025-10-05T11:00:00Z'},{r:'Daniel K.',rt:3,ti:'Good but not perfect',bo:'Sound is decent but the right earbud feels slightly loose after extended wear. Still decent value.',vp:false,ts:'2025-09-18T08:45:00Z'}],
    2:[{r:'Claire B.',rt:5,ti:'Best running shoes I\'ve owned',bo:'Incredible cushioning and support. Ran a 10k with no foot pain and sizing is true to size.',vp:true,ts:'2025-11-20T10:00:00Z'},{r:'Michael S.',rt:5,ti:'Brilliant grip and comfort',bo:'Used these on trail runs and road runs. Grip is excellent and they look great too.',vp:true,ts:'2025-11-01T09:15:00Z'},{r:'Amy N.',rt:4,ti:'Great shoes, wide fit',bo:'Very comfortable from the first wear with no break-in period needed. Slightly pricey but worth it.',vp:true,ts:'2025-10-14T16:00:00Z'},{r:'Tom H.',rt:5,ti:'Absolutely love these',bo:'My third pair. They last well and the support is second to none for long distance running.',vp:false,ts:'2025-09-22T12:00:00Z'}],
    3:[{r:'Rachel L.',rt:5,ti:'Makes a brilliant cup',bo:'Simple to use and cleans easily. The coffee tastes great and heats up quickly in the morning.',vp:true,ts:'2025-11-10T08:00:00Z'},{r:'Paul W.',rt:4,ti:'Does the job well',bo:'Good capacity and easy to set up. Only wish the keep-warm function lasted a bit longer.',vp:true,ts:'2025-10-22T13:00:00Z'},{r:'Helen F.',rt:4,ti:'Happy with this purchase',bo:'Compact size fits nicely on the counter. Coffee is consistently hot and the carafe pours cleanly.',vp:true,ts:'2025-10-08T09:30:00Z'},{r:'Gary T.',rt:3,ti:'Decent but lid rattles',bo:'Works fine but the lid on the carafe rattles slightly during brewing. Coffee quality is good though.',vp:false,ts:'2025-09-30T11:00:00Z'}],
    4:[{r:'Sophie C.',rt:5,ti:'Excellent grip and cushioning',bo:'Non-slip surface even during hot yoga. The thickness is perfect for joint support on hard floors.',vp:true,ts:'2025-11-12T10:00:00Z'},{r:'Liam G.',rt:4,ti:'Good quality mat',bo:'Durable and easy to clean. Slightly longer than expected which is actually a bonus for tall people.',vp:true,ts:'2025-10-30T15:00:00Z'},{r:'Natalie P.',rt:5,ti:'Best yoga mat I\'ve tried',bo:'Great grip, comfortable thickness, and the carrying strap is really useful. Highly recommend.',vp:true,ts:'2025-10-10T08:00:00Z'},{r:'Josh M.',rt:4,ti:'Solid everyday mat',bo:'Good value for money. Held up well over six months of regular use without wearing down.',vp:false,ts:'2025-09-25T14:00:00Z'}],
    5:[{r:'Kate A.',rt:5,ti:'Transformed my home office',bo:'Significant improvement to my posture since using this. Very sturdy and adjusts easily to any height.',vp:true,ts:'2025-11-18T09:00:00Z'},{r:'Ben H.',rt:5,ti:'Brilliant stand',bo:'Looks sleek, holds my laptop securely and the cable management hole is really handy.',vp:true,ts:'2025-11-02T11:00:00Z'},{r:'Lucy R.',rt:4,ti:'Great for working from home',bo:'Stable and easy to adjust. Just make sure to leave space underneath for ventilation.',vp:true,ts:'2025-10-15T14:00:00Z'},{r:'Oliver D.',rt:5,ti:'Worth every penny',bo:'Solid build, no wobble, great height options. My neck no longer aches after a full day of work.',vp:false,ts:'2025-09-28T10:00:00Z'}],
    6:[{r:'Fiona J.',rt:5,ti:'Keeps drinks cold all day',bo:'Filled it with ice water in the morning and it was still cold 8 hours later. Lid doesn\'t leak either.',vp:true,ts:'2025-11-14T08:30:00Z'},{r:'Ryan O.',rt:4,ti:'Good bottle, solid build',bo:'Feels durable and doesn\'t leave a metallic taste. The cap is a bit stiff at first but loosens up.',vp:true,ts:'2025-10-27T12:00:00Z'},{r:'Megan C.',rt:5,ti:'Love this bottle',bo:'Perfect size for the gym and hiking. Dishwasher safe which is a huge bonus.',vp:true,ts:'2025-10-09T09:00:00Z'},{r:'Chris B.',rt:4,ti:'Does exactly what it says',bo:'Keeps my tea hot for hours. Simple design with no unnecessary features. Great value.',vp:false,ts:'2025-09-20T15:00:00Z'}],
    7:[{r:'Anna P.',rt:4,ti:'Lovely lamp, great light',bo:'Bright, adjustable and the arm moves smoothly. USB charging port on the base is really convenient.',vp:true,ts:'2025-11-08T10:00:00Z'},{r:'Mark S.',rt:4,ti:'Good quality desk lamp',bo:'Nice clean design with multiple brightness levels. Wish it had more colour temperature options.',vp:true,ts:'2025-10-25T14:00:00Z'},{r:'Jo H.',rt:3,ti:'Fine but nothing special',bo:'Does the job but the arm is slightly wobbly at the lowest setting. Light quality is good though.',vp:true,ts:'2025-10-11T11:00:00Z'},{r:'Phil W.',rt:5,ti:'Excellent lamp for the price',bo:'Sturdy, bright and stylish. The touch controls work really well and the USB port charges my phone quickly.',vp:false,ts:'2025-09-24T09:00:00Z'}],
    8:[{r:'Zoe M.',rt:5,ti:'Perfect work and travel bag',bo:'Fits my 15 inch laptop perfectly. Loads of compartments and very comfortable shoulder straps.',vp:true,ts:'2025-11-16T09:30:00Z'},{r:'Aaron L.',rt:5,ti:'Built to last',bo:'Very sturdy zips, padded back panel, and looks professional enough for the office. Highly recommend.',vp:true,ts:'2025-10-29T13:00:00Z'},{r:'Isla K.',rt:4,ti:'Great backpack for the price',bo:'Spacious and well organised. The laptop sleeve is padded well. Slightly stiff to open when fully packed.',vp:true,ts:'2025-10-12T10:00:00Z'},{r:'Nathan E.',rt:4,ti:'Really impressed',bo:'Used this for a week of travel and it handled everything. Multiple pockets keep things well organised.',vp:false,ts:'2025-09-26T14:30:00Z'}],
    9:[{r:'Victoria B.',rt:5,ti:'Best smartwatch I\'ve owned',bo:'Tracks all my workouts accurately, battery lasts four days easily and the screen is vivid.',vp:true,ts:'2025-11-19T08:00:00Z'},{r:'Ian F.',rt:4,ti:'Excellent features for the price',bo:'Heart rate and sleep tracking are both accurate. Strap is comfortable and GPS locks on quickly.',vp:true,ts:'2025-11-03T11:00:00Z'},{r:'Grace N.',rt:5,ti:'Love everything about it',bo:'Notifications are clear, step counting is accurate and it looks great for both gym and office.',vp:true,ts:'2025-10-16T09:00:00Z'},{r:'Connor T.',rt:4,ti:'Really capable watch',bo:'Does everything I need. The health tracking features are genuinely useful and the app syncs quickly.',vp:false,ts:'2025-09-29T13:00:00Z'}],
    10:[{r:'Leanne S.',rt:5,ti:'Great full-body workout tool',bo:'Use these every day for home workouts. The different resistance levels mean I can progress steadily.',vp:true,ts:'2025-11-11T09:00:00Z'},{r:'Stuart M.',rt:4,ti:'Good quality bands',bo:'No snapping or rolling during use which was my main concern. Good range of resistance levels included.',vp:true,ts:'2025-10-24T14:00:00Z'},{r:'Hannah R.',rt:5,ti:'Essential home gym kit',bo:'Versatile, durable and the carry bag makes storage easy. Great for rehabilitation exercises too.',vp:true,ts:'2025-10-07T10:00:00Z'},{r:'Tim C.',rt:3,ti:'Decent but lightest band snapped',bo:'The medium and heavy bands are excellent but the lightest resistance band snapped after a month.',vp:false,ts:'2025-09-21T11:00:00Z'}],
    11:[{r:'Debbie L.',rt:5,ti:'Beautiful scents, great gift',bo:'Bought these as a gift and the recipient was thrilled. The scents are strong but not overpowering.',vp:true,ts:'2025-11-13T10:00:00Z'},{r:'Alice W.',rt:5,ti:'Absolutely gorgeous',bo:'The packaging is beautiful and the candles burn evenly with no tunnelling. Smell wonderful.',vp:true,ts:'2025-10-26T15:00:00Z'},{r:'Rose H.',rt:4,ti:'Lovely candles',bo:'Good burn time and the scents last throughout. One candle arrived slightly chipped but they\'re beautiful.',vp:true,ts:'2025-10-13T09:00:00Z'},{r:'Diane T.',rt:5,ti:'My favourite candles',bo:'Bought multiple times now. The scents fill the whole room and they last for hours. Highly recommend.',vp:false,ts:'2025-09-27T12:00:00Z'}],
    12:[{r:'Carl J.',rt:4,ti:'Stylish and functional',bo:'Good UV protection and the polarised lenses make a real difference in bright sunlight. Lightweight frame.',vp:true,ts:'2025-11-07T10:00:00Z'},{r:'Mel P.',rt:4,ti:'Great everyday sunglasses',bo:'Good fit, no slipping during outdoor activities. The case included is solid and protective.',vp:true,ts:'2025-10-23T13:00:00Z'},{r:'Tony G.',rt:3,ti:'Nice but feel a bit flimsy',bo:'Look good and the lenses are clear. Hinges feel lightweight so treat them with care.',vp:true,ts:'2025-10-06T11:00:00Z'},{r:'Laura B.',rt:5,ti:'Brilliant value',bo:'Wore these all summer, no scratches and still look brand new. Comfortable all day in high heat.',vp:false,ts:'2025-09-23T09:00:00Z'}],
    13:[{r:'Jamie S.',rt:5,ti:'Excellent everyday processor',bo:'Runs everything I throw at it without breaking a sweat. Great performance per pound.',vp:true,ts:'2025-11-17T09:00:00Z'},{r:'Marcus T.',rt:5,ti:'Smooth performer',bo:'Upgraded from a previous gen i5 and the difference is night and day. Great for gaming and productivity.',vp:true,ts:'2025-10-31T14:00:00Z'},{r:'Callum H.',rt:4,ti:'Good mid-range CPU',bo:'Solid all-rounder for gaming and content creation. Runs cool and quiet on a mid-range cooler.',vp:true,ts:'2025-10-14T10:00:00Z'},{r:'Priya K.',rt:4,ti:'Great value for money',bo:'Fast boot times, handles multitasking well and runs efficiently without needing a high-end cooler.',vp:false,ts:'2025-09-28T13:00:00Z'}],
    14:[{r:'Dave W.',rt:5,ti:'Brilliant 1080p gaming card',bo:'Handles every game I\'ve tried at max settings 1080p with ease. Quiet and runs cool too.',vp:true,ts:'2025-11-21T10:00:00Z'},{r:'Sam P.',rt:5,ti:'Massive upgrade',bo:'Coming from a GTX 1060 this is a huge leap. DLSS 3 is genuinely impressive in supported games.',vp:true,ts:'2025-11-04T09:00:00Z'},{r:'Niall B.',rt:4,ti:'Great card, excellent drivers',bo:'Performance is excellent and Nvidia driver support is rock solid. Very capable at 1440p too.',vp:true,ts:'2025-10-17T14:00:00Z'},{r:'Kerry M.',rt:4,ti:'Happy with the performance',bo:'Plays everything I want at high settings. The compact size made fitting it into my case easy.',vp:false,ts:'2025-09-30T10:00:00Z'}],
    15:[{r:'Evan C.',rt:5,ti:'Fast and stable',bo:'Running at XMP 6000MHz without any issues. Significant improvement in multitasking over my old DDR4.',vp:true,ts:'2025-11-09T09:00:00Z'},{r:'Rhys T.',rt:4,ti:'Great RAM kit',bo:'Easy to install and the XMP profile works perfectly. Low profile sticks fit with a large cooler.',vp:true,ts:'2025-10-22T11:00:00Z'},{r:'Abby L.',rt:5,ti:'Excellent performance',bo:'Zero issues after six months of heavy use. Fast, reliable and great value for DDR5.',vp:true,ts:'2025-10-05T10:00:00Z'},{r:'Joel W.',rt:4,ti:'Solid upgrade',bo:'Works flawlessly with my B760 board. Boot times noticeably faster than my previous kit.',vp:false,ts:'2025-09-19T14:00:00Z'}],
    16:[{r:'Colin R.',rt:5,ti:'Blazing fast speeds',bo:'Sequential reads well above 7000MB/s in benchmarks. Windows loads in seconds and games install quickly.',vp:true,ts:'2025-11-22T08:30:00Z'},{r:'Yvonne S.',rt:5,ti:'Best SSD I\'ve owned',bo:'Incredibly fast and runs at reasonable temperatures. The included heatspreader is a nice touch.',vp:true,ts:'2025-11-05T10:00:00Z'},{r:'Brendan F.',rt:5,ti:'Outstanding performance',bo:'Absolutely flies. Transferred 100GB in under 30 seconds and no throttling under sustained load.',vp:true,ts:'2025-10-18T13:00:00Z'},{r:'Tara M.',rt:4,ti:'Great SSD, strong value',bo:'Fast, compact and easy to install. Only four stars because the packaging was a bit battered on arrival.',vp:false,ts:'2025-10-01T09:00:00Z'}],
    17:[{r:'Neil G.',rt:4,ti:'Solid mainstream board',bo:'Good BIOS, straightforward setup and all components were recognised immediately. PCIe 5.0 slot is a bonus.',vp:true,ts:'2025-11-06T09:00:00Z'},{r:'Pat D.',rt:5,ti:'Great board for the money',bo:'Overclocking the RAM to XMP was simple and the board has run rock solid for three months.',vp:true,ts:'2025-10-20T14:00:00Z'},{r:'Shane K.',rt:4,ti:'Good feature set',bo:'Well laid out with plenty of fan headers and USB ports. BIOS is intuitive for a mainstream board.',vp:true,ts:'2025-10-03T10:00:00Z'},{r:'Kevin L.',rt:3,ti:'Fine but BIOS needs work',bo:'Board works well but the BIOS interface feels a bit dated. Performance is good once XMP is set up.',vp:false,ts:'2025-09-16T13:00:00Z'}],
    18:[{r:'Ray T.',rt:5,ti:'Silent and reliable',bo:'Completely silent under normal loads and barely audible under full stress. Fully modular design is excellent.',vp:true,ts:'2025-11-23T10:00:00Z'},{r:'Ciara B.',rt:5,ti:'Excellent power supply',bo:'Solid build quality and 80+ Gold efficiency is great. The modular cables are flexible and good quality.',vp:true,ts:'2025-11-06T13:00:00Z'},{r:'Donal H.',rt:4,ti:'Really happy with this PSU',bo:'Powers my RTX 4060 and i5-14400 build without any issues. Fan barely spins under light load.',vp:true,ts:'2025-10-19T09:00:00Z'},{r:'Siobhan W.',rt:4,ti:'Good value modular PSU',bo:'Quality cables, quiet fan and the 10-year warranty gives real confidence. Recommend for any mid-range build.',vp:false,ts:'2025-10-02T11:00:00Z'}],
    19:[{r:'Barry M.',rt:4,ti:'Great airflow, easy build',bo:'Tool-less drive installation and good cable management channels. Tempered glass side panel looks great.',vp:true,ts:'2025-11-24T09:00:00Z'},{r:'Aoife C.',rt:4,ti:'Spacious and well made',bo:'Plenty of room for my components and radiator support is excellent. Pre-installed fans perform well.',vp:true,ts:'2025-11-07T14:00:00Z'},{r:'Fergus R.',rt:3,ti:'Good case but dusty',bo:'Build quality is solid and airflow is fine. The dust filters are small and need cleaning frequently.',vp:true,ts:'2025-10-20T10:00:00Z'},{r:'Niamh S.',rt:5,ti:'Love this case',bo:'Clean look, easy to build in and the cable management options are excellent. Very happy with the quality.',vp:false,ts:'2025-10-03T13:00:00Z'}],
    20:[{r:'Declan P.',rt:5,ti:'Keeps my i5 very cool',bo:'Running at 28 degrees idle and 65 under full load. Incredibly quiet even at full speed.',vp:true,ts:'2025-11-25T08:00:00Z'},{r:'Sinead O.',rt:4,ti:'Good cooler for the price',bo:'Easy to install with clear instructions. Temperatures are significantly lower than the stock cooler.',vp:true,ts:'2025-11-08T10:00:00Z'},{r:'Ronan B.',rt:4,ti:'Solid performer',bo:'Compact enough to fit my case without clearance issues and keeps temperatures well in check.',vp:true,ts:'2025-10-21T14:00:00Z'},{r:'Eimear G.',rt:5,ti:'Great budget cooler',bo:'Much quieter than expected and temperatures are excellent for an air cooler at this price point.',vp:false,ts:'2025-10-04T09:00:00Z'}]
  };
  function getReviews(pid){const all=g('se_rv',null);if(!all){const init={};Object.keys(SR).forEach(k=>{init[k]=SR[k];});s('se_rv',init);}const stored=g('se_rv',{});const base=SR[pid]||[];const user=stored[pid]||[];const combined=[...user,...base];return combined.slice(0,20);}
  function addReview(rev){const stored=g('se_rv',{});if(!stored[rev.pid])stored[rev.pid]=[];stored[rev.pid].unshift(rev);s('se_rv',stored);}
  return{getUser,setUser,clearUser,requireAuth,login,guestLogin,logout,addAccount,changePw,deleteAccount,downloadData,
    getProds,setProds,syncProds,pushProds,getCart,setCart,cartCount,cartSub,addToCart,clearCart,
    getWL,setWL,toggleWL,getRecent,addRecent,getCookies,setCookies,getEvts,track,clearEvts,getTickets,addTicket,getOrders,addOrder,getReviews,addReview,isAdminArea,idxPath};
})();
